generateOres = true
blacklistedOres = []
spawnWithGuideBook = false
respawnWithGuideBook = false
disableFuelTooltips = true
disableItemTagTooltips = true
newVersionMessage = false
colorWaterLava = true
enableDebugCommands = false
